deployment:
  enabled: true
  replicas: 3

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.90.100.121"


additionalServices:
  traefik-ip-122:
    enabled: true
    type: LoadBalancer
    spec:
      loadBalancerIP: "10.90.100.122"
      ports:
        - name: web
          port: 80
          targetPort: web
          protocol: TCP
        - name: websecure
          port: 443
          targetPort: websecure
          protocol: TCP
          
installCRDs: true 

metrics:
  prometheus:
    service:
      enabled: true 

logs:
  access:
    enabled: true  

resources:
  limits:
    cpu: 100m
    memory: 512Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
