deployment:
  enabled: true
  replicas: 4

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik
  
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-ip-122

ports:
  web:
    port: 8000
    expose:
      default: true
      ip-122: true
      ip-123: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose:
      default: true
      ip-122: true
      ip-123: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.90.100.121"

  additionalServices:
    ip-122:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "10.90.100.122"
    ip-123:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "10.90.100.123"
        
installCRDs: true 

metrics:
  prometheus:
    service:
      enabled: true 

logs:
  access:
    enabled: true  

resources:
  limits:
    cpu: 100m
    memory: 512Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
