deployment:
  enabled: true
  replicas: 4

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.90.100.121"
        
installCRDs: true 

metrics:
  prometheus:
    service:
      enabled: true 

logs:
  access:
    enabled: true  

resources:
  limits:
    cpu: 100m
    memory: 512Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
