deployment:
  enabled: true
  replicas: 3

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.90.100.121"


extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: traefik-additional-lb
      namespace: traefik-ingress-controller
    spec:
      type: LoadBalancer
      loadBalancerIP: "10.90.100.122"
      ports:
        - name: web
          port: 80
          targetPort: 80
          protocol: TCP
        - name: websecure
          port: 443
          targetPort: 443
          protocol: TCP
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik-ingress-controller
          
installCRDs: true 

metrics:
  prometheus:
    service:
      enabled: true 

logs:
  access:
    enabled: true  

resources:
  limits:
    cpu: 100m
    memory: 512Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
