deployment:
  enabled: true
  replicas: 3

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

ports:
  web:
    expose:
      default: true
  websecure:
    expose:
      default: true
  private-web:
    port: 8000
    expose:
      default: false
      internal: true
    exposedPort: 80
  private-websecure:
    port: 8443
    expose:
      default: false
      internal: true
    exposedPort: 443


service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.90.100.121"

  additionalServices:
    internal:
      type: LoadBalancer
      spec:
        loadBalancerIP: "10.90.100.122"


installCRDs: true 

metrics:
  prometheus:
    service:
      enabled: true 

logs:
  access:
    enabled: true  

resources:
  limits:
    cpu: 100m
    memory: 512Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
