traefik:
  replicaCount: 1
  ingressClass:
    enabled: true
    isDefaultClass: true
    name: traefik
  service:
    enabled: true
    type: LoadBalancer  
    spec:
      LoadBalancerIP: "10.90.100.121"
  installCRDs: true  
  resources:
    limits:
      cpu: 100m
      memory: 512Mi