apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # the kind of the horizontal pod autoscaler
metadata:
  name: react-shop-fronted-hpa # the name of the hpa
  namespace: shop-online # the namespace that separate the pods between environments.
spec:
  scaleTargetRef:
    # after the deployment runs, the HPA will control the number of pods
    apiVersion: apps/v1
    kind: Deployment
    name: react-fronted # the name of the deployment from deployment file application
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # the time that the HPA will wait before another scaling
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15 # during the specified time, scaling will occur by 50% every 15 seconds
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # the kind of the horizontal pod autoscaler
metadata:
  name: backend-hpa # the name of the hpa
  namespace: shop-online # the namespace that separate the pods between environments.
spec:
  scaleTargetRef:
    # after the deployment runs, the HPA will control the number of pods
    apiVersion: apps/v1
    kind: Deployment
    name:  backend   # the name of the deployment from deployment file application
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # the time that the HPA will wait before another scaling
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15 # during the specified time, scaling will occur by 50% every 15 seconds
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # the kind of the horizontal pod autoscaler
metadata:
  name: mongodb-hpa # the name of the hpa
  namespace: shop-online # the namespace that separate the pods between environments.
spec:
  scaleTargetRef:
    # after the deployment runs, the HPA will control the number of pods
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb-deployment   # the name of the deployment from deployment file application
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # the time that the HPA will wait before another scaling
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15 # during the specified time, scaling will occur by 50% every 15 seconds
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
