kubeProxyReplacement: false

routingMode: tunnel
tunnelProtocol: vxlan

k8sNetworkPolicy:
  enabled: true

cni:
  install: true
  exclusive: true
  confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
  binPath: /var/lib/rancher/k3s/data/current/bin
  customConf: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/preserve-host: "true"
        traefik.ingress.kubernetes.io/router.tls: "true"
      className: traefik
      hosts:
        - cilium-ui.spider-shlomo.com
      tls:
        - secretName: cilium-ui-tls
          hosts:
            - cilium-ui.spider-shlomo.com
  metrics:
    enabled:
      - dns
      - drop
      - flow
      - icmp
      - tcp
      - udp
      - https
      - http

securityContext:
  # -- Run the pod with elevated privileges (needed for nsenter in init containers on master node)
  privileged: true

ipam:
  mode: kubernetes

envoy:
  enabled: true

envoyConfig:
  enabled: true
  secretsNamespace:
    create: true
    name: cilium-secrets
  retryInterval: 15s