apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appservices
  namespace: argocd 
spec:
  description: 'Project for appservices'
  sourceRepos:
    - '*'
  destinations:
   # - namespace: monitoring
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'