apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kyverno
  namespace: argocd 
spec:
  description: 'Project for kyverno policies'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'