apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  roles:
  # A role which provides full access to all users
  - name: full-access
    description: Full access to all applications in monitoring
    policies:
      - "p, proj:monitoring:full-access, applications, *, monitoring/*, allow"
