apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/shlomo-b/monitoring-stack-k3d.git
