apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: blackjack
spec:
  refreshInterval: 1m # how often the secret should be updated
  secretStoreRef: # reference to the secret store
    name: aws-secret-store
    kind: ClusterSecretStore
  #  kind: SecretStore
  target:
    name: aws-secret   # kube-secret its just name of the secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: DB-CREDENTIALS # name of the secret from aws secret manager