apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/homeProd-K3s.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://ui.charts.kafbat.io
      chart: kafka-ui
      targetRevision: 1.5.0
      helm:
        valueFiles:
          - $values/app-of-apps/chart-kafka-ui/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
