replicaCount: 1
serviceAccount:
  create: true
  name: kafka-ui
resources:
  limits:
    memory: "1"  
    cpu: "2Gi" 
  requests:
    memory: "500m"
    cpu: "1Gi"

service:
  type: LoadBalancer
  port: 8080