replicaCount: 1
serviceAccount:
  create: true
  name: kafka-ui
resources:
  limits:
    memory: 200m
    cpu: 512Mi  
  requests:
    memory: 200m
    cpu: 256Mi

service:
  type: LoadBalancer
  port: 8080