replicaCount: 1
serviceAccount:
  create: true
  name: kafka-ui
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: LoadBalancer
  port: 8080