apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: secretpass-full-outage
  namespace: chaos-mesh
spec:
  entry: full-outage
  templates:
    - name: full-outage
      templateType: Parallel
      children:
        - kill-backend
        - kill-frontend

    - name: kill-backend
      templateType: PodChaos
      deadline: 5m
      podChaos:
        action: pod-kill
        mode: all
        selector:
          namespaces:
            - secretpass
          labelSelectors:
            app: backend

    - name: kill-frontend
      templateType: PodChaos
      deadline: 5m
      podChaos:
        action: pod-kill
        mode: all
        selector:
          namespaces:
            - secretpass
          labelSelectors:
            app: frontend