apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh-secretpass
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
    app.kubernetes.io/managed-by: argocd
  finalizers:
    # When this Application is deleted, Argo CD also deletes its managed resources
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/homeProd-K3s.git
    path: ./chaos-mesh-secretpass
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
