apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: secretpass-chaos
  namespace: chaos-mesh
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  historyLimit: 5
  type: Workflow

  workflow:
    entry: rolling-chaos

    templates:
      - name: rolling-chaos
        templateType: Parallel
        children:
          - kill-backend
          - kill-frontend

      - name: kill-backend
        templateType: PodChaos
        podChaos:
          action: pod-kill
          mode: one
          selector:
            namespaces:
              - secretpass
            labelSelectors:
              app: backend

      - name: kill-frontend
        templateType: PodChaos
        podChaos:
          action: pod-kill
          mode: one
          selector:
            namespaces:
              - secretpass
            labelSelectors:
              app: frontend