appName: secretpass
namespace: secretpass

configmap:
  create: false

server:
  enabled: true
  ingress:
    enabled: false
  service:
    enabled: true
    serviceType: ClusterIP
    port: 5050
  image:
    name: shlomobarzili/secretpass-backend
    tag: latest 
  containerPort: 5050
  autoscaling:
    enabled: false
  affinity: {} 
  cm:
    enabled: true
  envVars:
    - name: BACKEND_URL
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: JWT_SECRET_KEY

    - name: MONGO_INITDB_HOST
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: MONGO_INITDB_HOST
      value: MONGO_INITDB_HOST

    - name: SAML_IDENTIFIER
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: SAML_IDENTIFIER
      value: https://secretpass.spider-shlomo.com/remote/saml/metadata
       
client:
  enabled: true
  ingress:
    enabled: false
  service:
    enabled: true
    serviceType: ClusterIP
    port: 3000
  image:
    name: shlomobarzili/secretpass-frontend
    tag: latest  
  env:
    - name: BACKEND_URL
      valueFrom:
        secretKeyRef:
            secretName: cronjob-credentials-fortigate-backup
            key: BACKEND_URL

  containerPort: 3000
  autoscaling:
    enabled: false
  affinity: {} 
  cm:
    enabled: false

db:  
  enabled: true
  service:
    enabled: true
    serviceType: ClusterIP
    port: 27017
  replicas: 1
  image:
    name: mongo
    tag: latest
  containerPort: 27017
  affinity: {}
  cm:
    enabled: false