appName: secretpass
namespace: secretpass

server:
  enabled: true
  revisionHistoryLimit: 0
  replicas: 2
  name: backend
  service:
    enabled: true
    serviceType: ClusterIP
    port: 5050
  image:
    name: shlomobarzili/secretpass-backend
    tag: v3.2.1
  containerPort: 5050
  autoscaling:
    enabled: false
  affinity: {} 
  cm:
    enabled: true
  envVars:
    - name: JWT_SECRET_KEY
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: JWT_SECRET_KEY

    - name: MONGO_INITDB_ROOT_USERNAME
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: MONGO_INITDB_ROOT_USERNAME

    - name: MONGO_INITDB_ROOT_PASSWORD
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: MONGO_INITDB_ROOT_PASSWORD

    - name: AWS_ACCESS_KEY_ID
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: AWS_ACCESS_KEY_ID

    - name: AWS_SECRET_ACCESS_KEY
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: AWS_SECRET_ACCESS_KEY

    - name: DB_NAME
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: DB_NAME

    - name: BUCKET_NAME
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: BUCKET_NAME

    - name: FERNET_KEY
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: FERNET_KEY

    - name: ADMIN_PASSWORD
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: ADMIN_PASSWORD

    - name: MICROSOFT_ENTRA_IDENTIFIER
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: MICROSOFT_ENTRA_IDENTIFIER

    - name: SAML_LOGIN_URL
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: SAML_LOGIN_URL 

    - name: SAML_CERTIFICATE
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: SAML_CERTIFICATE

    - name: MONGO_INITDB_HOST
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: MONGO_INITDB_HOST
      value: mongodb-service

    - name: SAML_IDENTIFIER
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: SAML_IDENTIFIER
      value: https://secretpass.spider-shlomo.com/remote/saml/metadata

    - name: SAML_REPLY_URL
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: SAML_REPLY_URL
      value: https://secretpass.spider-shlomo.com/remote/saml/acs

    - name: FRONTEND_URL_SAML
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: FRONTEND_URL_SAML
      value: https://secretpass.spider-shlomo.com
  resources:    
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi    

  ingress:
    enabled: true  
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/preserve-host: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
    host: secretpass.spider-shlomo.com
    paths:
    -  path: /api/
       pathType: Prefix
       serviceName: backend-svc
    -  path: /remote/saml/
       pathType: Prefix
       serviceName: backend-svc   

client:
  enabled: true
  revisionHistoryLimit: 0
  replicas: 2
  name: fronted
  service:
    enabled: true
    serviceType: ClusterIP
    port: 3000
  image:
    name: shlomobarzili/secretpass-frontend
    tag: v2.3.1  
  containerPort: 3000
  autoscaling:
    enabled: false
  affinity: {} 
  cm:
    enabled: true
  envVars:
    - name:  REACT_APP_API_URL
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: REACT_APP_API_URL
      value: https://secretpass.spider-shlomo.com
    - name: REACT_APP_ENABLE_SAML
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: REACT_APP_ENABLE_SAML
      value: true  
  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3   
  resources:
    requests:
      cpu: 250m
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 2Gi   
    
  ingress:
    enabled: true  
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/preserve-host: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
    host: secretpass.spider-shlomo.com
    paths:
    -  path: /
       pathType: Prefix
       serviceName: fronted-svc
    tls:
      - secretName: secretpass-app-tls
        hosts:
          - secretpass.spider-shlomo.com

db:  
  enabled: true
  revisionHistoryLimit: 0
  replicas: 1
  name: db
  service:
    enabled: true
    serviceType: ClusterIP
    port: 27017
  replicas: 1
  image:
    name: mongo
    tag: latest
  containerPort: 27017
  affinity: {}
  cm:
    enabled: true
  envVars:
    - name: MONGO_INITDB_ROOT_USERNAME
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: MONGO_INITDB_ROOT_USERNAME

    - name: MONGO_INITDB_ROOT_PASSWORD
      source: secretKeyRef
      nameVariables: secretspass-credentials
      key: MONGO_INITDB_ROOT_PASSWORD  

    - name: MONGO_INITDB_HOST
      source: configMapKeyRef
      nameVariables: secretpass-config
      key: MONGO_INITDB_HOST
      value: mongodb
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi    