appName: secretpass
namespace: secretpass

configmap:
  create: false

server:
  enabled: true
  ingress:
    enabled: false
  service:
    enabled: true
    serviceType: ClusterIP
    port: 5050
  image:
    name: shlomobarzili/secretpass-backend
    tag: latest
  containerPort: 5050
  autoscaling:
    enabled: false
  affinity: {}  
    

client:
  enabled: true
  ingress:
    enabled: false
  service:
    enabled: true
    serviceType: ClusterIP
    port: 3000
  image:
    name: shlomobarzili/secretpass-frontend
    tag: latest  
  containerPort: 3000
  autoscaling:
    enabled: false
  affinity: {}  
  
db:  
  enabled: true
  service:
    enabled: true
    serviceType: ClusterIP
    port: 27017
  replicas: 1
  image:
    name: mongo
    tag: latest
  containerPort: 27017
  affinity: {}