appName: first-helm-chart
namespace: dev

image:
  name: devopsjourney1/mywebapp
  tag: latest
service:
  port: 80
  targetPort: 80
  serviceType: LoadBalancer
ingress:
  enabled: false    
containerPort: 80  
ingress:
  enabled: false
configmap:
  name: default
  data:
    CUSTOM_HEADER: "This app was deployed using with helm"
