apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer-consumer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/homeProd-K3s.git
    path: ./k8s-apps/kafka-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
