apiVersion: apps/v1
kind: Deployment
metadata:
  name: cunsumer
  namespace: kafka
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cunsumer
  replicas: 1
  template:
    metadata:
      labels:
        app: cunsumer
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: consumer
        image: shlomobarzili/consumer:v2.0.0
        imagePullPolicy: Always
        ports:
        - name: cunsumer
          containerPort: 8001
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi  

        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_BOOTSTRAP_SERVERS

          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: TZ
---
apiVersion: v1
kind: Service
metadata:
  name: cunsumer-svc
  namespace: kafka
spec:
  selector:
    app: cunsumer
  type: LoadBalancer 
  loadBalancerIP: 10.90.100.126
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001