apiVersion: apps/v1
kind: Deployment
metadata:
  name: cunsumer
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: cunsumer
  replicas: 1
  template:
    metadata:
      labels:
        app: cunsumer
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: "kubernetes.io/hostname"
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: cunsumer  
   # spec:
      containers:
      - name: consumer
        image: shlomobarzili/consumer:v1.1.1
        imagePullPolicy: Always
        ports:
        - name: cunsumer
          containerPort: 8001
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi  

        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_BOOTSTRAP_SERVERS
---
apiVersion: v1
kind: Service
metadata:
  name: cunsumer-svc
  namespace: kafka
spec:
  selector:
    app: cunsumer
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001