apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: kafka
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: producer
  replicas: 2    
  template:
    metadata:
      labels:
        app: producer
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: "kubernetes.io/hostname"
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: producer  
   # spec:
      containers:
      - name: producer
        image: shlomobarzili/producer:v1.3.0
        imagePullPolicy: Always
        ports:
        - name: producer
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi  

        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_BOOTSTRAP_SERVERS

---
apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  namespace: kafka
spec:
  selector:
    app: producer
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000