apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-fortigate
  namespace: cronjob
spec:
  schedule: "0 0 * * 6"
  successfulJobsHistoryLimit: 1  # The number of successful Jobs that Kubernetes will retain in history
  failedJobsHistoryLimit: 1      # The number of failed Jobs that Kubernetes will retain in history
  ttlSecondsAfterFinished: 60    # The Job (and its pods) will be deleted 60 seconds after completion
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronjob
            image: shlomobarzili/cronjob:latest
            env:
              - name: USERNAME
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: USERNAME
                    
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: PASSWORD

              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: AWS_ACCESS_KEY_ID

              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: AWS_SECRET_ACCESS_KEY       

              - name: HOST
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: HOST

              - name: PORT
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: PORT

              - name: BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: cronjob-credentials
                    key: BUCKET_NAME