{{- range $name, $config := .Values }}
   {{- range $dns := $config.dnsNames }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $config.certificate_name }}
  namespace:  {{ $config.namespaces }}
spec:
  secretName: {{ $config.secretName }}
  revisionHistoryLimit: 1
  duration: 2160h
  renewBefore: 360h
  commonName: {{ $config.commonName }}
  dnsNames:  {{ $dns }}
  issuerRef:
    name: {{ $config.issuerRefName }}
    kind: ClusterIssuer
---

  {{- end }}
{{- end }}