{{- range $name, $config := .Values }}
apiVersion: external-secrets.io/v1
kind: Certificate
metadata:
  name: {{ $config.external_secret_name }}
  namespace: {{ $config.namespaces }}
spec:
  refreshInterval: {{ $config.refreshInterval }}
  secretStoreRef:
    name: {{ $config.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ $config.target }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $config.dataFrom.extract.key }}
---
  {{- end }}
{{- end }}


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secretpass-cert
  namespace: secretpass
spec:
  secretName: secretpass-app-tls
  revisionHistoryLimit: 1
  duration: 2160h
  renewBefore: 360h
  commonName: secretpass.spider-shlomo.com
  dnsNames:
  - secretpass.spider-shlomo.com
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
