{{- range $name, $config := .Values }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $config.certificate_name }}
  namespace: {{ $config.namespaces }}
spec:
  secretName: {{ $config.secretName }}
  revisionHistoryLimit: 1
  duration: 2160h
  renewBefore: 360h
  commonName: {{ $config.commonName }}
  dnsNames:
    {{- range $dns := $config.dnsNames }}
    - {{ $dns }}
    {{- end }}
  issuerRef:
    name: {{ $config.issuerRefName }}
    kind: ClusterIssuer
---
{{- end }}
