{{- range $name, $config := .Values }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $config.cronjob_name }}
  namespace: cronjob
  labels:
    app: {{ $config.cronjob_name }}
spec:
  schedule: "{{ $config.schedule }}"
  successfulJobsHistoryLimit: 1  # The number of successful Jobs that Kubernetes will retain in history
  failedJobsHistoryLimit: 1      # The number of failed Jobs that Kubernetes will retain in history
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60 # The Job (and its pods) will be deleted 60 seconds after completion
      template:
        spec:
{{- with $config.podSecurityContext }}
          securityContext:
{{ toYaml . | nindent 12 }}
{{- end }}
          restartPolicy: OnFailure
          containers:
            - name: cronjob
              image: "{{ $config.image.name }}:{{ $config.image.tag }}"
{{- with $config.securityContext }}
              securityContext:
{{ toYaml . | nindent 16 }}
{{- end }}
              env:
{{- range $env := $config.env }}
                - name: {{ $env.name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $env.secretName }}
                      key: {{ $env.key.name }}
{{- end }}
{{- if and $config.cm $config.cm.enabled $config.cm.data }}
              envFrom:
                - configMapRef:
                    name: cronjob-config-{{ $name }}
{{- end }}
{{- if and $config.volumeMounts $config.volumeMounts.enabled $config.volumeMounts.pvc }}
              volumeMounts:
                - name: cronjob-pvc-{{ $name }}
                  mountPath: {{ $config.volumeMounts.pvc.mountPath }}
{{- end }}
{{- if and $config.volumeMounts $config.volumeMounts.enabled $config.volumeMounts.pvc }}
          volumes:
            - name: cronjob-pvc-{{ $name }}
              persistentVolumeClaim:
                claimName: cronjob-pvc-{{ $name }}
{{- end }}

---
{{- end }}
