{{- range $name, $config := .Values }}
{{- if and $config.volumeMounts $config.volumeMounts.enabled $config.volumeMounts.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronjob-pvc-{{ $name }}
  namespace: cronjob
spec:
  {{- with $config.volumeMounts.pvc.accessModes }}
  accessModes:
    {{toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ $config.volumeMounts.pvc.size }}
  storageClassName: local-path
{{- end }}
---
{{- end }}