metallb:
  serviceAccount:
    create: true
  apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    # A name for the address pool. Services can request allocation
    # from a specific address pool using this name.
    name: first-pool
    namespace: metallb-system
  spec:
    # A list of IP address ranges over which MetalLB has
    # authority. You can list multiple ranges in a single pool, they
    # will all share the same settings. Each range can be either a
    # CIDR prefix, or an explicit start-end range of IPs.
    addresses:
    - 172.18.0.252/32
    - 172.18.0.100-172.18.0.150
    - 172.18.0.251/32
  