metallb:
  speaker:
    enabled: true
    serviceAccount:
        create: true
    resources:
       limits:
         cpu: 100m
         memory: 100Mi    
         
  controller:
    enabled: true  
    serviceAccount:
      create: true
    resources:
       limits:
         cpu: 100m
         memory: 100Mi  
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2
