metallb:
  crds:
    enabled: true
    validationFailurePolicy: Fail
    bgp:
      enabled: false
  speaker:
    enabled: true
    serviceAccount:
        create: true
    resources:
       limits:
         cpu: 100m
         memory: 100Mi    
    frr:
      enabled: false     
         
  controller:
    enabled: true  
    serviceAccount:
      create: true
    resources:
       limits:
         cpu: 100m
         memory: 100Mi
    frr:
      enabled: false      
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2
  frrk8s:
    enabled: false                 