apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-k8s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # The finalizer delete the application and resources
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/homeProd-K3s.git # the repo
    path: app-of-apps-test/applications
    targetRevision: HEAD
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'app/templates/**'
  destination:
    server: https://kubernetes.default.svc  # The cluster URL Argo CD will connect to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true