# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd-k8s
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io # The finalizer delete the application and resources
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/shlomo-b/homeProd-K3s.git # the repo
#     path: app-of-apps-test/applications
#     targetRevision: HEAD
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc  # The cluster URL Argo CD will connect to
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: all-apps-dev-prod
#   namespace: argocd
# spec:
#   generators:
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 - env: dev
#                 - env: prod
#           - git:
#               repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#               revision: HEAD
#               directories:
#                 - path: app-of-apps-test/*
#   template:
#     metadata:
#       name: '{{path.basename}}-{{env}}'
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#         targetRevision: HEAD
#         path: app-of-apps-test/{{path.basename}}
#         helm:
#           valueFiles:
#             - values-{{env}}.yaml
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: '{{env}}'
#       syncPolicy:
#         syncOptions:
#           - CreateNamespace=true
#         automated:
#           selfHeal: true
#           prune: true