istio-vs-blackjack:
  name: blackjack-vs
  namespace: blackjack
  host: blackjack-k3s.spider-shlomo.com
  gateway: istio-system/blackjack-gateway
  route:
    destination:
        host: blackjack
        port: 80
        