{{- range $name, $config := .Values }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $config.cronjob_name }}
  namespace: cronjob
  annotations:
    keel.sh/policy: "all"
    keel.sh/trigger: "poll"
    keel.sh/pollSchedule: "@every 3m"
spec:
  schedule: "{{ $config.schedule }}"
  successfulJobsHistoryLimit: 1  # The number of successful Jobs that Kubernetes will retain in history
  failedJobsHistoryLimit: 1      # The number of failed Jobs that Kubernetes will retain in history
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60 # The Job (and its pods) will be deleted 60 seconds after completion
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronjob
            image: "{{ $config.image.name }}:{{ $config.image.tag }}"
            env:
              {{- range $env := $config.env }}
              - name: {{ $env.name }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $env.secretName }}
                    key: {{ $env.key.name }}
            {{- end }}
---
{{- end }}
