# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd-k8s
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io # The finalizer delete the application and resources
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/shlomo-b/homeProd-K3s.git # the repo
#     path: app-of-apps-test/applications
#     targetRevision: HEAD
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc  # The cluster URL Argo CD will connect to
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: all-apps-dev-prod
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   generators:
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 - env: dev
#                 - env: prod
#                 - env: test
#           - git:
#               repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#               revision: HEAD
#               directories:
#                 - path: app-of-apps-test/*
#   template:
#     metadata:
#       name: '{{path.basename}}-{{env}}'
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#         targetRevision: HEAD
#         path: app-of-apps-test/{{path.basename}}
#         helm:
#           valueFiles:
#             - values-{{env}}.yaml
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: '{{env}}'
#       syncPolicy:
#         # syncOptions:
#         #   - CreateNamespace=true
#         automated:
#           selfHeal: true
#           prune: true
---

# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: all-apps
#   namespace: argocd
# spec:
#   generators:
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 - env: secrets-management
#                   chartPath: secrets-management
#                   valueFile: values.yaml
#                 # - env: certificates-management
#                 #   chartPath: certificates-management
#                 #   valueFile: values.yaml 
#                 # - env: dev
#                 #   chartPath: app
#                 #   valueFile: values-dev.yaml
#                 # - env: prod
#                 #   chartPath: app
#                 #   valueFile: values-prod.yaml
#                 # - env: test
#                 #   chartPath: app
#                 #   valueFile: values-test.yaml
#                 # - env: blackjack
#                 #   chartPath: blackjack
#                 #   valueFile: values-app.yaml 
#                 # - env: cronjob
#                 #   chartPath: cronjob
#                 #   valueFile: values.yaml  
#                 # - env: pool-alb
#                 #   chartPath: pool-alb
#                 #   valueFile: values.yaml
#                 # - env: secretpass
#                 #   chartPath: secretpass
#                 #   valueFile: values.yaml  
#           - git:
#               repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#               revision: HEAD
#               directories:
#                 - path: applications/*
#   template:
#     metadata:
#       name: '{{env}}'
#       labels:
#         argocd.argoproj.io/instance: '{{env}}'
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#         targetRevision: HEAD
#         path: applications/{{chartPath}}
#         helm:
#           valueFiles:
#             - '{{valueFile}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: '{{env}}'
#       syncPolicy:
#         syncOptions:
#           - CreateNamespace=true
#         automated:
#           selfHeal: true
#           prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/shlomo-b/homeProd-K3s.git
        revision: HEAD
        directories:
          - path: applications/*/*
  template:
    metadata:
      name: "{{path.basename}}"
      labels:
        app.kubernetes.io/managed-by: argocd
        argocd-project: "{{path[1]}}"
    spec:
      project: "{{path[1]}}"
      source:
        repoURL: https://github.com/shlomo-b/homeProd-K3s.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
