{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yourchart.fullname" (dict "name" .Values.client.name) }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.client.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.client.name }}
spec:
  revisionHistoryLimit: {{ .Values.client.revisionHistoryLimit }}
  {{- if (not .Values.client.autoscaling.enabled) }}
  replicas: {{ .Values.client.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
{{- with .Values.client.affinity }}
      affinity:
      {{ toYaml . | indent 4 }}
{{- end }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.client.image.name }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}

          env:
{{- range $env := (.Values.client.env | default list) }}
            - name: {{ $env.name }}
{{- if $env.value }}
              value: {{ $env.value | quote }}
{{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secretName }}
                  key: {{ $env.key }}
{{- end }}
{{- end }}

{{- $hasExtraSecret := and .Values.secret .Values.secret.enabled }}
{{- $hasCm := and .Values.client.cm .Values.client.cm.enabled .Values.client.cm.data }}
{{- if or $hasCm $hasExtraSecret }}
          envFrom:
{{- if $hasCm }}
            - configMapRef:
                name: config-{{ .Values.client.name }}
{{- end }}
{{- if $hasExtraSecret }}
            - secretRef:
                name: {{ .Values.secret.name | default (printf "secretpass-config-%s" .Values.client.name) }}
{{- end }}
{{- end }}

          ports:
            - containerPort: {{ .Values.client.containerPort }}
          {{- with .Values.client.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.client.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.client.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}

{{- end }}