{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yourchart.fullname" (dict "name" .Values.db.name) }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.db.name }}
spec:
  revisionHistoryLimit: {{ .Values.db.revisionHistoryLimit }}
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      {{- with .Values.db.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.db.image.name }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}

          env:
{{- range $env := (.Values.db.env | default list) }}
            - name: {{ $env.name }}
{{- if $env.value }}
              value: {{ $env.value | quote }}
{{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secretName }}
                  key: {{ $env.key }}
{{- end }}
{{- end }}

{{- $hasExtraSecret := and .Values.secret .Values.secret.enabled }}
{{- $hasCm := and .Values.db.cm .Values.db.cm.enabled .Values.db.cm.data }}
{{- if or $hasCm $hasExtraSecret }}
          envFrom:
{{- if $hasCm }}
            - configMapRef:
                name: config-{{ .Values.db.name }}
{{- end }}
{{- if $hasExtraSecret }}
            - secretRef:
                name: {{ .Values.secret.name | default (printf "secretpass-config-%s" .Values.db.name) }}
{{- end }}
{{- end }}

          ports:
            - containerPort: {{ .Values.db.containerPort }}

          {{- with .Values.db.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: mongo-pvc
              mountPath: /data/db

        volumes:
        - name: mongo-pvc
          persistentVolumeClaim:
            claimName: mongodb-pvc
{{- end }}