apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gha-runner-credentials
  namespace: gha
spec:
  refreshInterval: 168m # how often the secret should be updated
  secretStoreRef: # reference to the secret store
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: gha-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: RUNNER-Credentials