pools:
  traefikip:
    name: traefikip
    addresses:
      - 10.90.100.121/32
    autoAssign: false

  istio-gateway:
    name: istio-gateway
    addresses:
      - 10.90.100.200/32
    autoAssign: false  

  alb-resources:
    name: alb-resources
    addresses:
      - 10.90.100.130-10.90.100.149
    autoAssign: true

l2advertisement:
  services:
    ipAddressPools:
      - traefikip
      - alb-resources
      - istio-gateway


# services:
#   ipAddressPools:
#     - traefikip
#     - alb-resources