apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: v1.8.0
appVersion: v1.8.0
dependencies:
- name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.17.1