cert-manager:
  installCRDs: true
  serviceAccount:
    create: true
  resources:  
    requests:
      cpu: 10m
      memory: 80Mi
  affinity:
    nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: foo.bar.com/role
           operator: In
           values:
           - node2    

