cert-manager:
  replicaCount: 1
  serviceAccount:
    create: true
  installCRDs: true  
  resources:
    limits:
      cpu: 100m
      memory: 512Mi    

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - node1
              - node2