{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yourchart.fullname" (dict "name" .Values.server.name) }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.server.name }}
spec:
  revisionHistoryLimit: {{ .Values.server.revisionHistoryLimit }}
  {{- if (not .Values.server.autoscaling.enabled) }}
  replicas: {{ .Values.server.replicas }}
  {{- end}}
  selector:
    matchLabels:
      app:  {{ .Values.server.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.server.name }}
{{- with .Values.server.affinity }}
      affinity:
      {{toYaml . | indent 4}}   
{{- end}}      
    spec:
      containers:
      - name: backend
        image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: Always
        env:
            {{- range .Values.server.envVars }}
            - name: {{ .name }}
              valueFrom:
              {{- if eq .source "secretKeyRef" }}
                secretKeyRef:
                  name: {{ .nameVariables }}
                  key: {{ .key }}
              {{- else if eq .source "configMapKeyRef" }}
                configMapKeyRef:
                  name: {{ .nameVariables }}
                  key: {{ .key }}
              {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.server.containerPort }}
        resources:
          requests:
            memory: 100m
            cpu: 512Mi
          limits:
            memory: 500m
            cpu: 1Gi
{{- end }}
