{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  {{- if (not .Values.server.autoscaling.enabled) }}
  replicas: {{ .Values.server.replicas }}
  {{- end}}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
{{- with .Values.server.affinity }}
      affinity:
      {{toYaml . | indent 4}}   
{{- end}}      
    spec:
      containers:
      - name: app3
        image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: Always
        env:
            {{- range .Values.server.envVars }}
            - name: {{ .name }}
              valueFrom:
              {{- if eq .source "secretKeyRef" }}
                secretKeyRef:
                  name: {{ .nameVariables }}
                  key: {{ .key }}
              {{- else if eq .source "configMapKeyRef" }}
                configMapKeyRef:
                  name: {{ .nameVariables }}
                  key: {{ .key }}
              {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.server.containerPort }}
        resources:
          requests:
            memory: "100Mi"
            cpu: "70m"
          limits:
            memory: "128Mi"
            cpu: "100m"
{{- end }}
