{{- if .Values.server.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name:   {{ include "yourchart.fullname" (dict "name" .Values.server.name) }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.server.name }}
spec:
  selector:
    app:  {{ .Values.server.name }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
  type: {{ .Values.server.service.serviceType }}
  
{{- end }}
