apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgres
  namespace: wiki
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-postgres-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-postgres-config
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-postgres-config
                  key: POSTGRES_DB   
---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  namespace: wiki
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
