apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wiki
  namespace: wiki
spec:
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: ghcr.io/requarks/wiki:2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: aws-secret # reference from ExternalSecret
          #       key: MONGO_INITDB_ROOT_USERNAME
                

          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: aws-secret # reference from ExternalSecret
          #       key: MONGO_INITDB_ROOT_PASSWORD
                

            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_TYPE  

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_PORT

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_USER

            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_PASS

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: svc-wiki
  namespace: wiki
spec:
  selector:
    app: wiki
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
