apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cronjob
  namespace: cronjob
spec:
  refreshInterval: 1m # how often the secret should be updated
  secretStoreRef: # reference to the secret store
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: cronjob-credentials-fortigate-backup
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: BUCKET-CRONJOB

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cronjob
  namespace: cronjob
spec:
  refreshInterval: 1m # how often the secret should be updated
  secretStoreRef: # reference to the secret store
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: cronjob-credentials-juniper-backup
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: juniper-credentials