appName: secretpass
namespace: secretpass

client:
  enabled: true
  revisionHistoryLimit: 0
#  replicas: 2
  name: frontend
  annotations:
    configmap.reloader.stakater.com/reload: "config-frontend"
    secret.reloader.stakater.com/reload: "secretspass-credentials"
  service:
    enabled: true
    serviceType: ClusterIP
    port: 3000
  image:
    name: shlomobarzili/secretpass-frontend
    pullPolicy: IfNotPresent
    tag: v3.1.1
  containerPort: 3000
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 70
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 50
            periodSeconds: 15
      scaleDown:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 50
            periodSeconds: 15
  affinity: {} 
  env:
    - name: TZ
      value: "Asia/Jerusalem"
       
  cm:
    enabled: true
    data:
      REACT_APP_API_URL: https://secretpass.spider-shlomo.com
      REACT_APP_ENABLE_SAML: true
  readinessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
  livenessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3   
  resources:
    requests:
      cpu: 250m
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 2Gi   
    
  ingress:
    enabled: true  
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/preserve-host: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
    host: secretpass.spider-shlomo.com
    paths:
    -  path: /
       pathType: Prefix
       serviceName: frontend-svc
    tls:
      - secretName: secretpass-app-tls
        hosts:
          - secretpass.spider-shlomo.com