{{- range $name, $config := .Values }}
  {{- range $ns := $config.namespaces }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $config.external_secret_name }}
  namespace: {{ $ns }}
spec:
  refreshInterval: {{ $config.refreshInterval }}
  secretStoreRef:
    name: {{ $config.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ $config.target }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $config.dataFrom.extract.key }}
---
  {{- end }}
{{- end }}
