apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates-apps
  namespace: argocd
spec:
  project: appservices
  source:
    repoURL: https://github.com/shlomo-b/homeProd-K3s.git
    path: ./k8s-apps/manage-certificates-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blackjack
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true