apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blackjack-cert
  namespace: blackjack
spec:
  secretName: blackjack-tls
  duration: 2160h
  renewBefore: 360h
  commonName: blackjack-k3s.spider-shlomo.com
  dnsNames:
  - blackjack-k3s.spider-shlomo.com
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer