apiVersion: v1
kind: Service
metadata:
  name: traefik-lb
  namespace: kube-system
  labels:
    app: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
    - port: 443
      name: websecure
      targetPort: 443
      protocol: TCP
