

# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: cronjob-fortigate
#   namespace: cronjob
# spec:
#   refreshInterval: 168m # how often the secret should be updated
#   secretStoreRef: # reference to the secret store
#     name: aws-secret-store
#     kind: ClusterSecretStore
#   target:
#     name: cronjob-credentials-fortigate-backup
#     creationPolicy: Owner
#   dataFrom:
#     - extract:
#         key: BUCKET-CRONJOB

# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: cronjob-juniper
#   namespace: cronjob
# spec:
#   refreshInterval: 168h # how often the secret should be updated
#   secretStoreRef: # reference to the secret store
#     name: aws-secret-store
#     kind: ClusterSecretStore
#   target:
#     name: cronjob-credentials-juniper-backup
#     creationPolicy: Owner
#   dataFrom:
#     - extract:
#         key: juniper-credentials


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  refreshInterval: 168h # how often the secret should be updated
  secretStoreRef: # reference to the secret store
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: route53-access


---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-credentials
  namespace: monitoring
spec:
  refreshInterval: 168h # how often the secret should be updated
  secretStoreRef: # reference to the secret store
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keys # name of the secret from aws secret manager
