apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-ingress
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: platform-infra
  sources:
    - repoURL: https://github.com/shlomo-b/homeProd-K3s.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.30.5
      helm:
        valueFiles:
          - $values/app-of-apps/chart-istio-gateway-ingress/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
