# Helm values for CronJobs.
# env: list of env from secrets. provider.aws/azure/gcp: storage from respective secret.

backup-fortigate:
  cronjob_name: backup-fortigate
  namespaceOverride: ""
  annotations: 
    configmap.reloader.stakater.com/reload: "cronjob-config-backup-fortigate"
    secret.reloader.stakater.com/reload: 
      - "cronjob-credentials-fortigate-backup"
      - "cronjob-credentials-azure"

  serviceAccount:
    create: true
    name: ""
    labels: {}
    annotations: {}


  schedule: "*/1 * * * *" # every month at 00:30
  image:
    name: shlomobarzili/fortigate
    pullPolicy: IfNotPresent
    tag: v1.7.0

  env:
    # # default is INFO
    # - name: LOG_LEVEL
    #   value: DEBUG

    - name: USERNAME
      secretName: cronjob-credentials-fortigate-backup
      key: USERNAME
    - name: PASSWORD
      secretName: cronjob-credentials-fortigate-backup
      key: PASSWORD
    - name: HOST
      secretName: cronjob-credentials-fortigate-backup
      key: HOST
    - name: PORT
      secretName: cronjob-credentials-fortigate-backup
      key: PORT

  provider:
    aws:
      enabled: true
      secretName: cronjob-credentials-fortigate-backup
      credentials:
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        bucket_name: BUCKET_NAME
    azure:
      enabled: false
      secretName: cronjob-credentials-azure
      credentials:
        azure_tenant_id: AZURE_TENANT_ID
        azure_client_id: AZURE_CLIENT_ID
        azure_client_secret: AZURE_CLIENT_SECRET
        azure_storage_account: AZURE_STORAGE_ACCOUNT
        azure_storage_container: AZURE_STORAGE_CONTAINER
    gcp:
      enabled: false
      secretName: cronjob-credentials-gcp
      credentials:
        gcp_application_credentials: GCP_APPLICATION_CREDENTIALS
        gcp_bucket_name: GCP_BUCKET_NAME

  volumeMounts:
    enabled: true
    pvc:
      name: cronjob-pvc-backup-fortigate
      accessModes:
        - ReadWriteOnce
      mountPath: /app
      size: 300Mi

  cm:
    enabled: true
    data:
      PUSHGATEWAY_ADDR: "prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
      PUSHGATEWAY_JOB: "backup-fortigate"
      PUSHGATEWAY_INSTANCE: "backup-fortigate"
      FW_NAME: "FW-Shlomi #"
      
      # optional push metrics to pushgateway
      metrics-pushgw: "true"

      # optional upload the file backup to cloud aws/azure/gcp
      # If the value is false, the file will be saved in the container.
      aws: "true"
      azure: "false"
      gcp: "false"


  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

###---------backup-juniper--------###

backup-juniper:
  cronjob_name: backup-juniper
  namespaceOverride: ""
  annotations: 
    configmap.reloader.stakater.com/reload: "cronjob-config-backup-juniper"
    secret.reloader.stakater.com/reload: 
      - "cronjob-credentials-juniper-backup"
      - "cronjob-credentials-azure"

  serviceAccount:
    create: true
    name: ""
    labels: {}
    annotations: {}

  schedule: "*/1 * * * *" # every month at 00:00
  image:
    name: shlomobarzili/junipersw
    pullPolicy: IfNotPresent
    tag: v1.7.0

  env:
    # # default is INFO
    # - name: LOG_LEVEL
    #   value: "INFO"

    - name: USERNAME
      secretName: cronjob-credentials-juniper-backup
      key: USERNAME
    - name: PASSWORD
      secretName: cronjob-credentials-juniper-backup
      key: PASSWORD
    - name: HOST
      secretName: cronjob-credentials-juniper-backup
      key: HOST
    - name: PORT
      secretName: cronjob-credentials-juniper-backup
      key: PORT

  provider:
    aws:
      enabled: true
      secretName: cronjob-credentials-juniper-backup
      credentials:
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        bucket_name: BUCKET_NAME
    azure:
      enabled: false
      secretName: cronjob-credentials-azure
      credentials:
        azure_tenant_id: AZURE_TENANT_ID
        azure_client_id: AZURE_CLIENT_ID  
        azure_client_secret: AZURE_CLIENT_SECRET
        azure_storage_account: AZURE_STORAGE_ACCOUNT
        azure_storage_container: AZURE_STORAGE_CONTAINER
    gcp:
      enabled: false
      secretName:  cronjob-credentials-gcp
      credentials:
        gcp_application_credentials: GCP_APPLICATION_CREDENTIALS
        gcp_bucket_name: GCP_BUCKET_NAME

  volumeMounts:
    enabled: true
    pvc:
      name: cronjob-pvc-juniper
      accessModes:
        - ReadWriteOnce
      mountPath: /app
      size: 300Mi

  cm:
    enabled: true
    data:
      PUSHGATEWAY_ADDR: "prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
      PUSHGATEWAY_JOB: "backup-juniper"
      PUSHGATEWAY_INSTANCE: "backup-juniper"
      SW_NAME: "@Juniper_BB>"
      
      # optional push metrics to pushgateway
      metrics-pushgw: "true"

      # optional upload the file backup to cloud aws/azure/gcp
      # If the value is false, the file will be saved in the container.
      aws: "true"
      azure: "false"
      gcp: "false"

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
