apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blackjack
  namespace: blackjack
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - blackjack-k3s.spider-shlomo.com
    secretName: blackjack-tls
  rules:
  - host: blackjack-k3s.spider-shlomo.com
    http:
      paths:
        - path: /metrics
          pathType: Prefix
          backend:
            service:
              name: svc-blackjack
              port:
                number: 80

        - path: /presentation
          pathType: Prefix
          backend:
            service:
              name: svc-blackjack
              port:
                number: 80

        - path: /
          pathType: Exact
          backend:
            service:
              name: svc-blackjack
              port:
                number: 80