apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blackjack
  namespace: blackjack
  annotations:
    # annotations for keel to update the image
    keel.sh/policy: "all"
    keel.sh/trigger: "poll"
    keel.sh/pollSchedule: "@every 3m"
spec:
  selector:
    matchLabels:
      app: blackjack
  template:
    metadata:
      labels:
        app: blackjack
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - node1
                  - node2
      containers:
        - name: blackjack
          image: shlomobarzili/blackjack:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-blackjack 
  namespace: blackjack
spec:
  selector:
    app: blackjack
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30060
      targetPort: 80
