global:
  domain: argocd-k3s.spider-shlomo.com
  
configs:
  params:
    server.insecure: true
  cm:
    create: true
    accounts.shlomob: apiKey, login
    # SSO Configuration via AzureAd
    url: https://argocd-k3s.spider-shlomo.com
    dex.config: |
        logger:
          level: debug
          format: json
        connectors:
        - type: saml
          id: saml
          name: azure
          config:
            entityIssuer: https://argocd-k3s.spider-shlomo.com/api/dex/callback
            ssoURL: https://login.microsoftonline.com/a2724ae3-73eb-4b45-ba62-f432da279e2c/saml2
            ca: /etc/dex/certs/ca.crt
            requestedID: https://argocd-k3s.spider-shlomo.com/api/dex/callback
            usernameAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
            emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

  # RBAC for application argocd
  rbac:
    policy.default: role:none
    policy.csv: |
      p, role:readonly-monitoring, applications, get, monitoring/*, allow
      p, role:readonly-monitoring, applications, override, monitoring/*, allow
      p, role:readonly-monitoring, applications, action/*, monitoring/*, allow
      p, role:readonly-monitoring, repositories, get, *, allow
      p, role:readonly-monitoring, projects, get, monitoring, allow
      p, role:readonly-monitoring, logs, get, monitoring/*, allow
      p, role:admin, applications, create, */*, allow
      p, role:admin, applications, update, */*, allow
      p, role:admin, applications, delete, */*, allow
      p, role:admin, applications, sync, */*, allow
      p, role:admin, applications, override, */*, allow
      p, role:admin, applications, action/*, */*, allow
      p, role:admin, applicationsets, get, */*, allow
      p, role:admin, applicationsets, create, */*, allow
      p, role:admin, applicationsets, update, */*, allow
      p, role:admin, applicationsets, delete, */*, allow
      p, role:admin, certificates, create, *, allow
      p, role:admin, certificates, update, *, allow
      p, role:admin, certificates, delete, *, allow
      p, role:admin, clusters, create, *, allow
      p, role:admin, clusters, update, *, allow
      p, role:admin, clusters, delete, *, allow
      p, role:admin, repositories, create, *, allow
      p, role:admin, repositories, update, *, allow
      p, role:admin, repositories, delete, *, allow
      p, role:admin, projects, create, *, allow
      p, role:admin, projects, update, *, allow
      p, role:admin, projects, delete, *, allow
      p, role:admin, accounts, update, *, allow
      p, role:admin, gpgkeys, create, *, allow
      p, role:admin, gpgkeys, delete, *, allow
      p, role:admin, exec, create, */*, allow
      g, "Shlomo_lab@spider-shlomo.com", role:admin
      g, "AlinaB@spider-shlomo.com", role:readonly-monitoring
    scopes: '[email]'

# Ingress for argo cd  
server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/preserve-host: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
    extraTls:
        - hosts:
            - argocd-k3s.spider-shlomo.com
          secretName: argocd-tls
  service:
    type: ClusterIP
    servicePortHttp: 80
    servicePortHttps: 443

# responsible for authenticating users
dex:
  volumes:
    - name: sso-cert
      secret:
        secretName: external-secrets-argocd # reference the secret name 

  # Mount the SSO certificate to Dex, making it available in the container     
  volumeMounts:
    - name: sso-cert
      mountPath: /etc/dex/certs
      readOnly: true