prometheus-cert:
  certificate_name: prometheus-cert
  namespaces: monitoring
  secretName: prometheus-tls
  secretStoreRefName: aws-secret-store
  commonName: prometheus-k3s.spider-shlomo.com
  dnsNames: 
  - prometheus-k3s.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer