prometheus-cert:
  certificate_name: prometheus-cert
  namespaces: monitoring
  secretName: prometheus-tls
  commonName: prometheus-k3s.spider-shlomo.com
  dnsNames: 
  - prometheus-k3s.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer

blackjack-cert:
  certificate_name: blackjack-cert
  namespaces: blackjack
  secretName: blackjack-tls
  commonName: blackjack-k3s.spider-shlomo.com
  dnsNames: 
  -  blackjack-k3s.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer

argocd-cert:
  certificate_name: argocd-cert
  namespaces: argocd
  secretName: argocd-tls
  commonName: argocd-k3s.spider-shlomo.com
  dnsNames: 
  -  argocd-k3s.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer

grafana-cert:
  certificate_name: grafana-cert
  namespaces: monitoring
  secretName: grafana-tls
  commonName: grafana-k3s.spider-shlomo.com
  dnsNames: 
  -  grafana-k3s.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer

uptime-kuma-cert:
  certificate_name: uptime-kuma-cert
  namespaces: monitoring
  secretName: uptime-kuma-tls
  commonName: uptime-kuma-k3s.spider-shlomo.com
  dnsNames: 
  -  uptime-kuma-k3s.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer

secretpass-cert:
  certificate_name: secretpass-cert
  namespaces: secretpass
  secretName: secretpass-app-tls
  commonName: secretpass.spider-shlomo.com
  dnsNames: 
  -  secretpass.spider-shlomo.com
  issuerRefName: letsencrypt-dns-issuer