{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
{{- with .Values.db.affinity }}
      affinity:
      {{toYaml . | indent 4}}   
{{- end}}      
    spec:
      containers:
      - name: app
        image: "{{ .Values.db.image.name }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.db.containerPort }}
        resources:
          requests:
            memory: "100Mi"
            cpu: "70m"
          limits:
            memory: "128Mi"
            cpu: "100m"

{{- end }}