{{- if .Values.db.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yourchart.fullname" (dict "name" .Values.db.name) }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.service.port }}              
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP
  type: {{ .Values.db.service.serviceType }} 

{{- end }}
