appName: apphub
namespace: apphub


apphub:
  enabled: true
  revisionHistoryLimit: 0
#  replicas: 2
  name: apphub
  # annotations:
  #   configmap.reloader.stakater.com/reload: "config-backend"
  #   secret.reloader.stakater.com/reload: "secretspass-credentials"
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true  

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

  service:
    enabled: true
    serviceType: LoadBalancer
    port: 8092
  image:
    name: shlomobarzili/apphub
    pullPolicy: IfNotPresent
    tag: v1.0.1
  containerPort: 8092
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 70
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 50
            periodSeconds: 15
      scaleDown:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 50
            periodSeconds: 15
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master
                  - master3
  env:
    # # default is INFO
    # - name: LOG_LEVEL
    #   value: "INFO"
    - name: TZ
      value: "Asia/Jerusalem" 


    - name: APPHUB_USER
      secretName:  apphub
      key: APPHUB_USER

    - name: APPHUB_PASSWORD
      secretName:  apphub
      key: APPHUB_PASSWORD

    - name: MONGO_HOST
      secretName:  apphub
      key: MONGO_HOST

    - name: MONGO_INITDB_ROOT_USERNAME
      secretName:  apphub
      key: MONGO_INITDB_ROOT_USERNAME

    - name: MONGO_INITDB_ROOT_PASSWORD
      secretName:  apphub
      key: MONGO_INITDB_ROOT_PASSWORD

      
  # provider:
  #   aws:
  #     enabled: true
  #     secretName: secretspass-credentials
  #     credentials:
  #       aws_access_key_id: AWS_ACCESS_KEY_ID
  #       aws_secret_access_key: AWS_SECRET_ACCESS_KEY
  #       bucket_name: BUCKET_NAME
  #   azure:
  #     enabled: false
  #     secretName: cronjob-credentials-azure
  #     credentials:
  #       azure_tenant_id: AZURE_TENANT_ID
  #       azure_client_id: AZURE_CLIENT_ID
  #       azure_client_secret: AZURE_CLIENT_SECRET
  #       azure_storage_account: AZURE_STORAGE_ACCOUNT
  #       azure_storage_container: AZURE_STORAGE_CONTAINER
  #   gcp:
  #     enabled: false 
  #     secretName: cronjob-credentials-gcp
  #     credentials:
  #       gcp_application_credentials: GCP_APPLICATION_CREDENTIALS
  #       gcp_bucket_name: GCP_BUCKET_NAME    

  cm:
    enabled: true
    data:
      USE_MONGODB: true
      MONGO_DB: apphub     

  resources:    
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi