backup-fortigate:
  cronjob_name: backup-fortigate
  schedule: "30 0 1 * *" # every month at 00:30
  image:
    name: shlomobarzili/fortigate-backup
    tag: latest

  env:
    - name: USERNAME
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: USERNAME
    - name: PASSWORD
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: PASSWORD
    - name: AWS_ACCESS_KEY_ID
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: AWS_SECRET_ACCESS_KEY
    - name: HOST
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: HOST