apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  namespace: secretpass
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - secretpass-backend.spider-shlomo.com
    secretName: secretpass-app-tls-backend
  rules:
  - host: secretpass-backend.spider-shlomo.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend-svc
              port:
                number: 5050
        - path: /remote/saml/
          pathType: Prefix
          backend:
            service:
              name: backend-svc
              port:
                number: 5050         
        # - path: /metrics
        #   pathType: Exact
        #   backend:
        #     service:
        #       name: lab4-backend-svc
        #       port:
        #         number: 5050

        # - path: /api/users
        #   pathType: Exact
        #   backend:
        #     service:
        #       name: lab4-backend-svc
        #       port:
        #         number: 5050

        # - path: /api/products
        #   pathType: Exact
        #   backend:
        #     service:
        #       name: lab4-backend-svc
        #       port:
        #         number: 5050

        # - path: /api/register
        #   pathType: Exact
        #   backend:
        #     service:
        #       name: lab4-backend-svc
        #       port:
        #         number: 5050        

        # - path: /api/login
        #   pathType: Exact
        #   backend:
        #     service:
        #       name: lab4-backend-svc
        #       port:
        #         number: 5050              