apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: secretpass
  labels:
    app: mongodb
spec:
  # create dns name for each pod mongodb
  serviceName: mongodb-service
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: shlomobarzili/mongodb:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: secretspass-credentials
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secretspass-credentials
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_INITDB_HOST
            valueFrom:
              configMapKeyRef:
                name: secretpass-config
                key: MONGO_INITDB_HOST

        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db # default path should be /data/db its for mongodb
       # command: ["mongod", "--replSet", "rs0"]  
  # create PVC for each pod mongodb
  volumeClaimTemplates:
    - metadata: 
        name: mongo-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path   # reference from StorageClass defult k3s
        resources:
          requests:
            storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: secretpass
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017