apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: secretpass
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: secretspass-credentials
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secretspass-credentials
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_INITDB_HOST
            valueFrom:
              configMapKeyRef:
                name: secretpass-config
                key: MONGO_INITDB_HOST

        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db # default path should be /data/db its for mongodb
      volumes:
      - name: mongo-pvc
        persistentVolumeClaim:
          claimName: mongodb-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: secretpass
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017