apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted-secretpass
  namespace: secretpass
  # annotations:
  #   # annotations for keel to update the image
  #   keel.sh/policy: "all"
  #   keel.sh/trigger: "poll"
  #   keel.sh/pollSchedule: "@every 3m"
spec:
  selector:
    matchLabels:
      app: fronted
  template:
    metadata:
      labels:
        app: fronted
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: "kubernetes.io/hostname"
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: react-app    
  #  spec:
      containers:
      - name: fronted
        image: shlomobarzili/secretpass-fronted:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: secretpass-config
                key: REACT_APP_API_URL

---
apiVersion: v1
kind: Service
metadata:
  name: fronted-svc
  namespace: secretpass
spec:
  selector:
    app: fronted
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000   # the port svc that expose
      targetPort: 3000 # the port of the pod