# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: fronted-hpa
#   namespace: secretpass
# spec:
#   scaleTargetRef:
#     # after the deployment runs, the HPA will control the number of pods
#     apiVersion: apps/v1
#     kind: Deployment
#     name: fronted-secretpass # the name of the deployment from deployment file application
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
#   behavior:
#     scaleUp:
#       stabilizationWindowSeconds: 60 # the time that the HPA will wait before another scaling
#       policies:
#         - type: Percent
#           value: 50
#           periodSeconds: 15 # during the specified time, scaling will occur by 50% every 15 seconds
#     scaleDown:
#       stabilizationWindowSeconds: 60
#       policies:
#         - type: Percent
#           value: 50
#           periodSeconds: 15

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: secretpass
spec:
  scaleTargetRef:
    # after the deployment runs, the HPA will control the number of pods
    apiVersion: apps/v1
    kind: Deployment
    name:  backend-secretpass
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # the time that the HPA will wait before another scaling
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15 # during the specified time, scaling will occur by 50% every 15 seconds
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb-hpa
  namespace: secretpass
spec:
  scaleTargetRef:
    # after the deployment runs, the HPA will control the number of pods
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # the time that the HPA will wait before another scaling
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15 # during the specified time, scaling will occur by 50% every 15 seconds
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
