apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/homeProd-K3s.git
      targetRevision: HEAD
      ref: values
    - repoURL:  https://github.com/actions-runner-controller
      chart: actions-runner-controller
      targetRevision: 0.23.7
      helm:
        valueFiles:
          - $values/app-of-apps/chart-runner/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
