prometheus:
  enabled: true
  serviceAccount:
    create: true  

  replicaCount: 1

  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.144"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 80
    servicePort: 80
    serviceTargetPort: 80
    hostPort: 80

  persistence:
    type: pvc
    enabled: true
    size: 10Gi

  prometheus.yml:
    enabled: true
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"

  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: false  