prometheus:
  enabled: true
  serviceAccount:
    create: true  
  server:
    global:
        scrape_interval: 15s
        scrape_timeout: 10s
    enabled: true
    service:
      type: LoadBalancer
      loadBalancerIP: "172.18.0.144"
      port: 9090
      targetPort: 9090
      servicePort: 9090
    persistentVolume:
      enabled: true
      size: 10Gi
  serverFiles:    
    prometheus.yml:
      rule_files:
        - /etc/config/prometheus.yml
      scrape_configs:
        - job_name: prometheus
          metrics_path: /metrics
          static_configs:
            - targets:
              - prometheus:9090
        - job_name: grafana
          metrics_path: /metrics
          static_configs:
            - targets:
              - grafana:3000      


  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: false