prometheus:
  enabled: true
  serviceAccount:
    create: true  
  server:
    global:
        scrape_interval: 15s
        scrape_timeout: 10s
        evaluation_interval: 15s
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/preserve-host: "true"
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
          - prometheus-k3s.spider-shlomo.com
      path: /
      pathType: Prefix    
      tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus-k3s.spider-shlomo.com
    service:
        enabled: true
        type: ClusterIP
        targetPort: 3000
    persistentVolume:
      enabled: true
      size: 10Gi
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'prometheus'
          metrics_path: '/metrics'
          static_configs:
            - targets: 
                - "prometheus-k3s.spider-shlomo.com:443"
          scheme: https
          
        - job_name: grafana
          metrics_path: /metrics
          static_configs:
            - targets:
                - "grafana-k3s.spider-shlomo.com:443"
          scheme: https      

        - job_name: "backend"
          metrics_path: "/metrics"
          static_configs:
              - targets:
                - "backend-k3s.spider-shlomo.com:443"
          scheme: https

        - job_name: 'node-exporter-nodes'
          metrics_path: /metrics
          static_configs:
            - targets:
                - "master-eks:9100"
                - "node1:9100"
                - "node2:9100"
                - "node3:9100"

        - job_name: 'traefik'
          metrics_path: /metrics
          static_configs:
            - targets:
                - "10.43.174.163:9100"

        - job_name: 'kubernetes-service-endpoints'
          honor_labels: true

          kubernetes_sd_configs:
            - role: endpoints

          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
              action: drop
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: (.+?)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: service
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: node

#---------------outside the network----------------#

        - job_name: "shlomo-pc"
          metrics_path: "/metrics"
          static_configs:
            - targets:
                - "10.0.11.250:9182"

  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: true
    service:
      type: ClusterIP
      port: 9100
      targetPort: 9100
      PortName: metrics
      name: node-exporter