prometheus:
  enabled: true
  serviceAccount:
    create: true  
  server:
    global:
        scrape_interval: 15s
        scrape_timeout: 10s
        evaluation_interval: 15s
    enabled: true
    service:
      type: LoadBalancer
      loadBalancerIP: "172.18.0.144"
      port: 9090
    #  targetPort: 9090
      servicePort: 9090
    persistentVolume:
      enabled: true
      size: 10Gi
  serverFiles:    
    prometheus.yml:
      rule_files:
        - /etc/config/prometheus.yml
      scrape_configs:
        - job_name: prometheus
          metrics_path: /metrics
          static_configs:
            - targets:
              - prometheus-server:9090
        - job_name: grafana
          metrics_path: /metrics
          static_configs:
            - targets:
              - grafana:3000
        - job_name: node-exporter
          metrics_path: /metrics
          static_configs:
            - targets:
              - prometheus-prometheus-node-exporter:9100      


        - job_name: 'blackjack.spider-shlomo.com'
          metrics_path: "/metrics"
          static_configs:
            - targets: ['blackjack.spider-shlomo.com:443']
          scheme: https

        - job_name: 'backend.spider-shlomo.com'
          metrics_path: "/metrics"
          static_configs:
            - targets: ['backend.spider-shlomo.com:443']
          scheme: https    

        - job_name: "shlomo-pc"
          metrics_path: "/metrics"
          static_configs:
            - targets: ["10.0.11.250:9182"]   
        
        - job_name: "pods blackjack in eks"
          metrics_path: "/metrics"
          static_configs:
            - targets: ["node-exporter.spider-shlomo.com:30910"]

        - job_name: 'react-shop-backend-minikube'
          metrics_path: "/metrics"
          static_configs:
            - targets: ['192.168.49.2:30056']          


  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: true
    service:
      type: ClusterIP
      port: 9100
      targetPort: 9100
      PortName: metrics
      name: node-exporter
