prometheus:
  serviceAccount:
    create: true
  replicaCount: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.148"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 9090
    targetPort: 9090
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    storageClass: ""
  # extraScrapeConfigs:
  #   enabled: true
  #   configs:
  #     - job_name: "custom-job"
  #       static_configs:
  #         - targets: ["172.18.0.100:8080"]