prometheus:
  enabled: true
  serviceAccount:
    create: true  

  replicaCount: 1

  server:
    enabled: true
    service:
      type: LoadBalancer
      loadBalancerIP: "172.18.0.144"
      port: 9090
      targetPort: 9090
      servicePort: 9090
    persistentVolume:
      enabled: true
      size: 10Gi
    extraScrapeConfigs: |
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets:
                - "localhost:9090"   
        - job_name: "x"
          static_configs:
            - targets:
                - "localhost:9090"           

  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: false