prometheus:
  serviceAccount:
    create: true
  replicaCount: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.148"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 9090
    targetPort: 9090
    servicePort: 9090
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    storageClass: ""
  prometheus.yml:
    enabled: true
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090