prometheus:
  enabled: true
  serviceAccount:
    create: true  
  server:
    global:
        scrape_interval: 15s
        scrape_timeout: 10s
        evaluation_interval: 15s
    enabled: true
    service:
      type: LoadBalancer
      loadBalancerIP: 10.90.100.111
      targetPort: 9090
      port: 9090
      servicePort: 9090
      loadBalancerClass: ""
      loadBalancerSourceRanges: []
      containerPortName: metrics
    persistentVolume:
      enabled: true
      size: 10Gi
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'prometheus'
          metrics_path: '/metrics'
          static_configs:
            - targets: 
                - "prometheus-server:9090"

        - job_name: grafana
          metrics_path: /metrics
          static_configs:
            - targets:
                - "grafana:3000"

        - job_name: "backend-shop-online.spider.local"
          metrics_path: "/metrics"
          static_configs:
              - targets: 
                - "10.90.100.149:5050"

        - job_name: 'node-exporter-nodes'
          metrics_path: /metrics
          static_configs:
            - targets:
                - "master-eks:9100"
                - "node1:9100"
                - "node2:9100"
                - "node3:9100"
          
# #---------------outside the network----------------#

#         - job_name: 'blackjack.spider-shlomo.com'
#           metrics_path: "/metrics"
#           static_configs:
#             - targets: ['blackjack.spider-shlomo.com:443']
#           scheme: https

#         - job_name: 'backend.spider-shlomo.com'
#           metrics_path: "/metrics"
#           static_configs:
#             - targets: ['backend.spider-shlomo.com:443']
#           scheme: https    

        - job_name: "shlomo-pc"
          metrics_path: "/metrics"
          static_configs:
            - targets:
                - "10.0.11.250:9182"

  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: true
    service:
      type: ClusterIP
      port: 9100
      targetPort: 9100
      PortName: metrics
      name: node-exporter
