prometheus:
  enabled: true
  serviceAccount:
    create: true  

  replicaCount: 1

  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.144"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 80
    servicePort: 80
    serviceTargetPort: 9090
    hostPort: 9090

  persistentVolume:
    enabled: true
    mountPath: /data
    size: 10Gi
    accessModes:
      - ReadWriteOnce

  prometheus.yml:
    enabled: true
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"

  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: true  