prometheus:
  enabled: true
  serviceAccount:
    create: true  

  replicaCount: 1

  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.144"
    port: 80
    targetPort: 9090  # Prometheus default port

  persistence:
    enabled: true
    size: 10Gi
    mountPath: /prometheus  # Ensure correct data storage

  prometheus.yml:
    enabled: true
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"
      - job_name: "x"
        static_configs:
          - targets:
              - "localhost:9090"        

  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false  

  prometheus-node-exporter:
    enabled: false  