appName: first-helm-chart
namespace: default

replicas: 1
image:
  name: devopsjourney1/mywebapp
  tag: latest
service:
  port: 80
  targetPort: 80
  serviceType: LoadBalancer
containerPort: 80  
ingress:
  enabled: false
autoscaling:
  enabled: false
affinity: {}
