appName: first-helm-chart
namespace: default

image:
  name: devopsjourney1/mywebapp
  tag: latest
service:
  port: 80
  targetPort: 80
  serviceType: LoadBalancer
containerPort: 80  
ingress:
  enabled: false
autoscaling:
  enabled: false
configmap:
  name: default
  data:
    CUSTOM_HEADER: "This app was deployed using with helm"
