{{- if .Values.podmonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitoring
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
  - port: {{ .Values.appName }}
    path: /metrics
    interval: {{ .Values.podmonitor.interval }}
{{- end }}