apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-externalsecrets-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/homeProd-K3s.git
    path: ./manage-secrets-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  #  namespace: shop-online
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      selfHeal: true 
      prune: true