apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/homeProd-K3s.git
      targetRevision: HEAD
      ref: values
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: zookeeper
      targetRevision: 13.8.4
      helm:
        valueFiles:
          - $values/app-of-apps/chart-zookeeper/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
