{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:   {{ include "yourchart.fullname" (dict "name" .Values.client.name) }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.client.name }}
spec:
  revisionHistoryLimit: {{ .Values.client.revisionHistoryLimit }}
  {{- if (not .Values.client.autoscaling.enabled) }}
  replicas: {{ .Values.client.replicas }}
  {{- end}}
  selector:
    matchLabels:
      app:  {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
{{- with .Values.client.affinity }}
      affinity:
      {{toYaml . | indent 4}}   
{{- end}}      
    spec:
      containers:
      - name: app
        image: "{{ .Values.client.image.name }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: Always
        env:
            {{- range .Values.client.envVars }}
            - name: {{ .name }}
              valueFrom:
              {{- if eq .source "secretKeyRef" }}
                secretKeyRef:
                  name: {{ .nameVariables }}
                  key: {{ .key }}
              {{- else if eq .source "configMapKeyRef" }}
                configMapKeyRef:
                  name: {{ .nameVariables }}
                  key: {{ .key }}
              {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.client.containerPort }}
        resources:
          requests:
            memory: "100Mi"
            cpu: "70m"
          limits:
            memory: "128Mi"
            cpu: "100m"

        readinessProbe:
          httpGet:
            path: {{ .Values.client.readinessPath }}
            port: {{ .Values.client.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: {{ .Values.client.readinessPeriod }}
          timeoutSeconds: {{ .Values.client.readinessTimeout }}
          successThreshold: {{ .Values.client.readinessSuccess }}
          failureThreshold: {{ .Values.client.readinessFailure }}

        livenessProbe:
          httpGet:
            path: {{ .Values.client.livenessPath }}
            port: {{ .Values.client.containerPort }}
          initialDelaySeconds: {{ .Values.client.livenessDelay }}
          periodSeconds: {{ .Values.client.livenessPeriod }}
          timeoutSeconds: {{ .Values.client.livenessTimeout }}
          successThreshold: {{ .Values.client.livenessSuccess }}
          failureThreshold: {{ .Values.client.livenessFailure }}  

{{- end }}