{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  {{- if (not .Values.client.autoscaling.enabled) }}
  replicas: {{ .Values.client.replicas }}
  {{- end}}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
{{- with .Values.client.affinity }}
      affinity:
      {{toYaml . | indent 4}}   
{{- end}}      
    spec:
      containers:
      - name: app
        image: "{{ .Values.client.image.name }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: Always
        env:
          {{- range $env := .Values.client.env }}
          - name: {{ $env.name }}
            valueFrom:
              secretKeyRef:
                name: {{ $env.secretName }}
                key: {{ $env.key }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.client.containerPort }}
        resources:
          requests:
            memory: "100Mi"
            cpu: "70m"
          limits:
            memory: "128Mi"
            cpu: "100m"

{{- end }}