apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/homeProd-K3s.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.keel.sh
      chart: keel
      targetRevision: 1.0.5
      helm:
        valueFiles:
          - $values/app-of-apps/chart-keel/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
