appName: first-helm-chart
namespace: prod

image:
  name: grafana/grafana
  tag: latest
service:
  port: 80
  targetPort: 3000
  serviceType: LoadBalancer
ingress:
  enabled: false  
containerPort: 3000
ingress:
  enabled: false
configmap:
  name: default
  data:
    CUSTOM_HEADER: "This app was deployed using with helm"
