global:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - external-secrets
              - external-secrets-webhook
              - external-secrets-cert-controller

enabled: true
replicaCount: 1
installCRDs: true
scopedRBAC: true

serviceAccount:
  create: true
  name: external-secrets

extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: aws-secret-store
      namespace: external-secrets
    spec:
      provider:
        aws:
          service: SecretsManager
          region: us-east-1
          auth:
            secretRef:
              accessKeyIDSecretRef:
                name: aws-secret
                key: accessKeyId
                namespace: external-secrets
              secretAccessKeySecretRef:
                name: aws-secret
                key: secretAccessKey
                namespace: external-secrets

