global:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - external-secrets
              - external-secrets-webhook
              - external-secrets-cert-controller

enabled: true
replicaCount: 2
installCRDs: true
scopedRBAC: true

serviceAccount:
  create: true
  name: external-secrets
