global:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - external-secrets
              - external-secrets-webhook
              - external-secrets-cert-controller

enabled: true
replicaCount: 1
installCRDs: true
scopedRBAC: true

serviceAccount:
  create: true
  name: external-secrets

clusterSecretStore:
  name: aws-secret-store
  namespace: external-secrets
  region: us-east-1
  accessKeySecretName: aws-secret
  accessKeyIdKey: accessKeyId
  secretAccessKeyKey: secretAccessKey


