external-secrets:
  enabled: true
  replicaCount: 1
  installCRDs: true
  scopedRBAC: true
  serviceAccount:
    create: true
    name: external-secrets
  
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - external-secrets
          topologyKey: "kubernetes.io/hostname"