# Pool for monitoring
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: monitoring
  namespace: metallb-system
spec:
  addresses:
  - 10.90.100.110-10.90.100.119
  autoAssign: false
---
# Pool for Argo CD
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: argocd-ip
  namespace: metallb-system
spec:
  addresses:
  - 10.90.100.200/32
  autoAssign: false

---
# Pool for other services
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: alb-resources
  namespace: metallb-system
spec:
  addresses:
    - 10.90.100.121-10.90.100.150
  autoAssign: true
---
# L2Advertisement to use both pools
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - monitoring
  - argocd-ip
  - alb-resources