# apiVersion: v2
# name: gha
# description: A Helm chart for actions-runner-controller
# type: application
# version: 0.11.0
# appVersion: "0.11.0"
# dependencies:
# - name: actions-runner-controller
#   repository: https://actions-runner-controller.github.io/actions-runner-controller
#   version: 0.11.0