# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gha-runner
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/shlomo-b/homeProd-K3s.git
#     path: app-of-apps/chart-gha
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: gha-runner
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       selfHeal: true 
#       prune: true