appName: dev
namespace: dev

image:
  name: grafana/grafana
  tag: latest

service:
  containerPort: 3000
  targetPort: 3000
  serviceType: LoadBalancer
configmap:
  name: app2
  data:
    CUSTOM_HEADER: "welcome to dev"