appName: prod
namespace: prod

image:
  name: devopsjourney1/mywebapp
  tag: latest

service:
  serviceType: LoadBalancer

serviceType: LoadBalancer
configmap:
  name: app1
  data:
    CUSTOM_HEADER: "welcome to Prod"