cronjob-services:
  description: 'Project for cronjob'
  repo: "*"
  destination:
    namespace: "*"
    server: "*"
  clusterResourceWhitelist:
    group: "*"
    kind: "*"

monitoring:
  description: 'Project for monitoring'
  repo: "*"
  destination:
    namespace: "*"
    server: "*"
  clusterResourceWhitelist:
    group: "*"
    kind: "*"

platform-infra:
  description: 'Project for platform-infra'
  repo: "*"
  destination:
    namespace: "*"
    server: "*"
  clusterResourceWhitelist:
    group: "*"
    kind: "*"

appservices:
  description: 'Project for appservices'
  repo: "*"
  destination:
    namespace: "*"
    server: "*"
  clusterResourceWhitelist:
    group: "*"
    kind: "*"