{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yourchart.fullname" (dict "name" .Values.server.name) }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.server.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.server.name }}
spec:
  revisionHistoryLimit: {{ .Values.server.revisionHistoryLimit }}
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
    spec:
      {{- with .Values.server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: backend
          image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}

          env:
{{- range $env := (.Values.server.env | default list) }}
            - name: {{ $env.name }}
{{- if $env.value }}
              value: {{ $env.value | quote }}
{{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secretName }}
                  key: {{ $env.key }}
{{- end }}
{{- end }}

{{- if .Values.server.provider.aws.enabled }}
            # AWS storage and secret keys
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.provider.aws.secretName }}
                  key: {{ .Values.server.provider.aws.credentials.aws_access_key_id }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.provider.aws.secretName }}
                  key: {{ .Values.server.provider.aws.credentials.aws_secret_access_key }}
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.provider.aws.secretName }}
                  key: {{ .Values.server.provider.aws.credentials.bucket_name }}
{{- end }}

{{- if .Values.server.provider.azure.enabled }}
                # Azure storage
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.server.provider.azure.secretName }}
                      key: {{.Values.server.provider.azure.credentials.azure_tenant_id }}
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.server.provider.azure.secretName }}
                      key: {{.Values.server.provider.azure.credentials.azure_client_id }}
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.server.provider.azure.secretName }}
                      key: {{.Values.server.provider.azure.credentials.azure_client_secret }}
                - name: AZURE_STORAGE_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.server.provider.azure.secretName }}
                      key: {{.Values.server.provider.azure.credentials.azure_storage_account }}
                - name: AZURE_STORAGE_CONTAINER
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.server.provider.azure.secretName }}
                      key: {{.Values.server.provider.azure.credentials.azure_storage_container }}
{{- end }}

{{- if.Values.server.provider.gcp.enabled }}
                # GCP storage
                - name: GCP_APPLICATION_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name:  {{.Values.server.provider.gcp.secretName }}
                      key:  {{.Values.server.provider.gcp.credentials.gcp_application_credentials }}
                - name: GCP_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.server.provider.gcp.secretName }}
                      key: {{.Values.server.provider.gcp.credentials.gcp_bucket_name }}
{{- end }}

{{- $hasExtraSecret := and .Values.secret .Values.secret.enabled }}
{{- $hasCm := and .Values.server.cm .Values.server.cm.enabled .Values.server.cm.data }}
{{- if or $hasCm $hasExtraSecret }}
          envFrom:
{{- if $hasCm }}
            - configMapRef:
                name: config-{{ .Values.server.name }}
{{- end }}
{{- if $hasExtraSecret }}
                - secretRef:
                    name: {{ .Values.secret.name | default (printf "secretpass-config-%s" .Values.server.name) }}
{{- end }}
{{- end }}

          ports:
            - containerPort: {{ .Values.server.containerPort }}

          {{- with .Values.server.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}