apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: node-exporter # the namespace that separates the pods between environments.
spec:
  selector:
    matchLabels:
      app: node-exporter
  replicas: 1  # the pods will be created and running.
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9100
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---     
apiVersion: v1
kind: Service
metadata:
  name: svc-node-exporter
  namespace: node-exporter
spec:
  selector: 
    app: node-exporter
  type: NodePort  
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30910
