apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 3.3.2
appVersion: 3.3.2
dependencies:
- name: loki
  repository: https://grafana.github.io/helm-charts
  version: 6.24.0