apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 3.0.0
appVersion: 3.0.0
dependencies:
- name: loki
  repository: https://grafana.github.io/helm-charts
  version: 6.5.0