apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 3.3.2
appVersion: 3.3.2
dependencies:
- name: loki
  repository: https://github.com/grafana/loki
  version: 6.25.0
  condition: loki.enabled # only install if etrics-server is enabled