apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/shlomo-b/homeProd-K3s.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.30.1
      helm:
        valueFiles:
          - $values/app-of-apps/chart-loki/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
