loki:
  loki:
    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  deploymentMode: SingleBinary
  
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
    
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi