loki:
  deploymentMode: SimpleScalable
  loki:
    enabled: true
    serviceAccount:
      create: true
      name: loki-access-to-s3
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: index_
            period: 24h
          object_store: s3
          schema: v13
    storage:
      bucketNames:
        chunks: loki-storge
        ruler: s3-loki
        admin: s3-loki
      type: s3
      s3:
        s3: true
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1
        accessKeyId: access-key
        secretAccessKey: secret-access-key


  read:
    legacyReadTarget: false
    replicas: 1
    service:
      enabled: true
      type: ClusterIP
      port: 3100 # the port svc that expose and use for helthcheck
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi   

  write:
    replicas: 1 
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi   

  backend:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi  

  resultsCache:
    enabled: false
  #   cache:
  #     enableFifoCache: true
  #     fifoCacheConfig:
  #       maxSizeBytes: 1073741824  # 1GB
  #       validity: 1h  
  # limits_config:
  #   maxCacheFreshnessPerQuery: 1m  # רענון כל דקה    

  chunksCache:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false
  gateway:
    enabled: false  



      