deploymentMode: SimpleScalable

serviceAccount:
  create: true
  name: loki-access-to-s3
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/s3-loki
loki:
  loki:
    auth_enabled: false
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: s3
          schema: v13
    storage:
      bucketNames:
        chunks: loki-storge
        ruler: s3-loki
        admin: s3-loki
      type: s3
      s3:
        region: us-east-1

  read:
    legacyReadTarget: false
    replicas: 1

  write:
    replicas: 1

  backend:
    replicas: 1

  gateway:
    enabled: false

  chunksCache:
    enabled: false

  resultsCache:
    enabled: false

  lokiCanary:
    enabled: false

  test:
    enabled: false