loki:
  serviceAccount:
    create: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 3100
  storage:
    type: s3
    s3:
      s3: null
      endpoint: null
      region: 
      secretAccessKey: null
      accessKeyId: null
      signatureVersion: null
      s3ForcePathStyle: false
      insecure: false
      http_config: {}
      # -- Check https://grafana.com/docs/loki/latest/configure/#s3_storage_config for more info on how to provide a backoff_config
      backoff_config: {}
      disable_dualstack: false
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
      admin_api_directory: /var/loki/admin

