loki:
  serviceAccount:
    create: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 3100
  schemaConfig:
    configs:
      - from: 2020-10-01
        store: bigquery