loki:
  serviceAccount:
    create: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 3100
  chemaConfig:
    configs:
      - from: 2024-06-01 #The date from which this schema configuration applies.
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h #The time period for creating new index tables, here 24h (daily).

 