loki:
  deploymentMode: SimpleScalable
  loki:
    auth_enabled: false
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: s3
          schema: v13
    storage:
      bucketNames:
        chunks: loki-storge
        ruler: s3-loki
        admin: s3-loki
      type: s3

  read:
    legacyReadTarget: false
    replicas: 1
  gateway:
    enabled: false
    replicas: 1  
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: "172.18.0.149"
      loadBalancerClass: ""
    # loadBalancerSourceRanges: []
      port: 3100
      targetPort: 3100
  write:
    replicas: 1  

  backend:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 1

  serviceAccount:
    create: true
    name: loki-access-to-s3
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/s3-loki