# loki:
#   loki:
#     auth_enabled: false

#     schemaConfig:
#       configs:
#         - from: "2024-01-01"
#           store: tsdb
#           index:
#             prefix: loki_index_
#             period: 24h
#           object_store: s3
#           schema: v13

#     persistence:
#       type: pvc
#       enableStatefulSetAutoDeletePVC: true
#       enabled: true
#       size: 10Gi  
#       storageClass: null   

#     storage:
#       bucketNames:
#         chunks: tikal-loki

#     bucket:
#       ruler: tikal-loki-bucket
#       admin: tikal-loki-bucket
#       type: s3

#     s3:
#       s3: s3://eu-central-1
#       endpoint: s3.eu-central-1.amazonaws.com
#       region: eu-central-1
#       secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
#       accessKeyId: ${AWS_ACCESS_KEY_ID}


loki:
  loki:
    auth_enabled: false
    deploymentMode: SingleBinary  # חשוב שזה יהיה בהתחלה
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper  # שינוי מ-tsdb ל-boltdb-shipper
          object_store: filesystem  # שינוי מ-s3 ל-filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h

    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi