loki:
  serviceAccount:
    create: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 3100
  storage:
    type: "s3"
    s3:
      region: "us-east-1"
    bucketNames:
      chunks: devsecops-shlomo-tf
      ruler:  devsecops-shlomo-tf
      admin:  devsecops-shlomo-tf 

