loki:
  loki:
    serviceAccount:
      create: true
      name: loki-access-to-s3
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/s3-loki
    auth_enabled: false
    read:
      replicas: 1

    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: s3
          schema: v13

    # persistence:
    #   type: pvc
    #   enableStatefulSetAutoDeletePVC: true
    #   enabled: true
    #   size: 10Gi  
    #   storageClass: null   

    storage:
      bucketNames:
        chunks: loki-storge

    bucket:
      ruler: s3-loki
      admin: s3-loki
      type: s3

    # s3:
    #   s3: s3://eu-central-1
    #   endpoint: s3.eu-central-1.amazonaws.com
    #   region: eu-central-1
    #   secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    #   accessKeyId: ${AWS_ACCESS_KEY_ID}
