loki:
  deploymentMode: SingleBinary  # חשוב שזה יהיה בהתחלה

  loki:
    auth_enabled: false
    
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: boltdb-shipper  # שינוי מ-tsdb ל-boltdb-shipper
          object_store: filesystem  # שינוי מ-s3 ל-filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h

    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi