loki:
  loki:
    auth_enabled: true

    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: s3
          schema: v13

    storage:
      bucketNames:
        chunks: tikal-loki

    bucket:
      ruler: tikal-loki-bucket
      admin: tikal-loki-bucket
      type: s3

    s3:
      s3: s3://eu-central-1
      endpoint: s3.eu-central-1.amazonaws.com
      region: eu-central-1
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
