loki:
  loki:
    config:
      storage_config:
        filesystem:
          directory: /var/loki/chunks
    
    deploymentMode: SingleBinary
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi