loki:
  global:
    deploymentMode: SimpleScalable
  loki:
    extraEnv:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: accessKeyId
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: secretAccessKey
    enabled: true
    serviceAccount:
      create: true
      name: loki-access-to-s3
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: index_
            period: 24h
          object_store: s3
          schema: v13
    storage:
      bucketNames:
        chunks: loki-storge
        ruler: s3-loki
        admin: s3-loki
      type: s3
      s3:
        s3: true
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1   
        # access_key_id:
        # valueFrom:
        #   secretKeyRef:
        #     name: aws-secret
        #     key: accessKeyId
        #   secret_access_key:
        #     valueFrom:
        #       secretKeyRef:
        #         name: aws-secret
        #         key: secretAccessKey
  read:
    legacyReadTarget: false
    replicas: 1
    service:
      enabled: true
      type: ClusterIP
      port: 3100 # the port svc that expose and use for helthcheck
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi   

  write:
    replicas: 1 
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi   

  backend:
    replicas: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi  

  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false
  gateway:
    enabled: false  



      