loki:
  serviceAccount:
    create: true
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    port: 80
    targetPort: 3100
  persistence:
    enabled: true
    storageSize: 10Gi
    storageClass: null
  storage:
    type: filesystem  # or any other supported storage type
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules