loki:
  serviceAccount:
    create: true
  enabled: true  
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    port: 80
    targetPort: 3100
  persistence:
    enabled: true
    size: 10Gi
  storage:
    bucketNames:
      chunks: aws-bucket-name
      ruler: aws-bucket-name
      admin: aws-bucket-name
    type: s3
    s3:
      region: aws-region
  auth_enabled: false