loki:
  global:
    deploymentMode: SimpleScalable
  loki:
    enabled: true
    serviceAccount:
      create: true
      name: loki-access-to-s3
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: index_
            period: 24h
          object_store: s3
          schema: v13
    storage:
      bucketNames:
        chunks: loki-storge
        ruler: s3-loki
        admin: s3-loki
      type: s3
      s3:
        s3: s3://s3.us-east-1
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1   
        secretAccessKey: ${ACCESS_KEY_ID}
        accessKeyId: ${SECRET_ACCESS_KEY}
  read:
    legacyReadTarget: false
    replicas: 2
    service:
      enabled: true
      type: ClusterIP
      port: 3100 # the port svc that expose and use for helthcheckd
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi
    # affinity:
    # # verify the pods will run on different nodes
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchLabels:
    #             app.kubernetes.io/component: read
    #         topologyKey: kubernetes.io/hostname

  write:
    replicas: 2
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi
    service:
      enabled: true
      type: ClusterIP
      port: 3100
    # affinity:
    # # verify the pods will run on different nodes
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchLabels:
    #             app.kubernetes.io/component: write
    #         topologyKey: kubernetes.io/hostname     


  backend:
    replicas: 1
    persistence:
      enabled: true
      volumeClaimsEnabled: true
      size: 10Gi  

  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false
  gateway:
    enabled: false  



      