loki:
  serviceAccount:
    create: true
  enabled: true  
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "172.18.0.149"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    port: 80
    targetPort: 3100
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "standard"  # או שם ה-StorageClass המתאים לסביבה שלך
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      shared_store: filesystem
    filesystem:
      directory: /data/loki/chunks
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
