apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  namespace: shop-online
  labels:
    app: mongodb-lab4
spec:
  serviceName: mongodb-service
  selector:
    matchLabels:
      app: mongodb-lab4
  template:
    metadata:
      labels:
        app: mongodb-lab4
    spec:
      containers:
      - name: mongodb
        image: shlomobarzili/mongodb:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: aws-secret # reference from ExternalSecret
                key: MONGO_INITDB_ROOT_USERNAME
                
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aws-secret # reference from ExternalSecret
                key: MONGO_INITDB_ROOT_PASSWORD

          - name: MONGO_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: var-shop-online # reference from ConfigMap
                key: MONGO_DB_HOST

        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db # default path should be /data/db its for mongodb
  volumeClaimTemplates:
        - metadata: 
          name: mongo-pvc
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: shop-online
spec:
  selector:
    app: mongodb-lab4
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017