uptime-kuma:
  enabled: true
  serviceAccount:
    create: true  
  service:
    type: NodePort
    port: 3001
    nodePort: 30056
  volume:
    enabled: true
    accessMode: ReadWriteOnce
    size: 4Gi
    accessModes:
      - ReadWriteMany
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - node1
            - node2    