{{- if or .Values.client.cm.enabled .Values.server.cm.enabled .Values.db.cm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretpass-config
  namespace: {{ .Values.namespace | default "default" }}
data:
{{- $all := concat (default (list) .Values.client.envVars) (default (list) .Values.server.envVars) (default (list) .Values.db.envVars) }}
{{- range $all }}
  {{- if eq .source "configMapKeyRef" }}
  {{ .key }}: {{ .value | default "" | quote }}
  {{- end }}
{{- end }}
{{- end }}
