{{- if or .Values.client.cm.enabled .Values.server.cm.enabled .Values.db.cm.enabled .Values.configmap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace | default "default" }}
data:
{{ toYaml .Values.configmap.data | nindent 2 }}
{{- end }}
