{{- if or .Values.client.cm.enabled .Values.server.cm.enabled .Values.db.cm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretpass-config
  namespace: {{ .Values.namespace }}
data:
{{- range or .Values.client.envVars .Values.server.envVars .Values.db.envVars }}
  {{- if eq .source "configMapKeyRef" }}
  {{ .key }}: {{ .value | default "" | quote }}
  {{- end }}
{{- end }}
{{- end }}
