name: apply appset

on:
  push: 
    branches: [ "main" ]
    paths:
      - 'applications/**'
  # pull_request:
  #   paths:
  #     - 'applications/**'

jobs:
  argo_upgrade:
    name: 'applicationset'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Show GitHub Runner IP
      run: |
        curl -s https://checkip.amazonaws.com

    - name: Setup K3s Kubeconfig
      run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          echo "KUBECONFIG is set for K3s"

    - name: Verify K3s Connection
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl cluster-info
        kubectl get nodes

    - name: apply appset
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'  
      run: |
        kubectl apply -f appset.yaml
      working-directory: ./applications