apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.clusterSecretStore.accessKeySecretName }}
            key: {{ .Values.clusterSecretStore.accessKeyIdKey }}
            namespace: {{ .Values.clusterSecretStore.namespace }}
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.accessKeySecretName }}
            key: {{ .Values.clusterSecretStore.secretAccessKeyKey }}
            namespace: {{ .Values.clusterSecretStore.namespace }}
