apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
  namespace: test
type: Opaque
data:
  access-key: QUtJQVNFNldLSFNOU0NRQ0dCNkc=
  secret-access-key: eXYvT0VJd0c4b3VkYzF2UjV6amhvc01jaUFTNXdIMFBJQ1ZLL1EwcQ==